from mongo_migrate.base_migrate import BaseMigration
from config import freelance_db

class Migration(BaseMigration):
    def upgrade(self):
        """
        Creates a compound unique index on the 'jobs' collection, 
        ensuring that the combination of job_id and user_id is unique 
        across all documents.
        """
        # Index creation syntax: takes a list of (field, direction) tuples.
        # Direction 1 is ascending. The unique=True flag enforces the constraint.
        freelance_db.jobs.create_index(
            [("job_id", 1), ("user_id", 1)],
            unique=True
        )
        
    def downgrade(self):
        """
        Drops the compound index created in the upgrade method.
        The name is automatically generated by MongoDB based on the fields and directions.
        """
        # MongoDB automatically names the index based on the fields and directions:
        freelance_db.jobs.drop_index("job_id_1_user_id_1")
        
    def comment(self):
        return 'create_job_id_and_user_id_compound_unique_index'
